
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  data:
    rest:
      base-path: /v2
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:h2:file:~/test
#  devtools:
#    restart:
#      enabled: false